---
title: "Lecture-13: Conditional expectation"
author: "Parimal Parag"
---

# Conditional expectation conditioned on a random vector

Let $X: \Omega \to \R^n$ be a random vector defined on a probability space $(\Omega, \sF, P)$. Recall that the projection $\pi_i: \R^n \to \R$ of $n$-dimensional vector $X$ on its $i$th component gives $X_i = \pi_i(X)$, and it is a Borel measurable function. It follows that $X_i = \pi_i\circ X$ is a random variable for each $i \in [n]$. Further the event space generated by random vectors $X$ is given by

::: rem
Let $(A_i \in \sF:  i \in [n])$ be an $n$-length sequence of events, then $X = (\Ind{A_i}: i \in [n])$ is a random vector, and the smallest event space generated by this random vector is $\sigma(X) = \sigma(A_1, \dots, A_n)$.
:::

::: defn
Consider a random variable $X:\Omega \to\R$ such that $\E\abs{X} < \infty$ and a random vector $Y:\Omega \to \R^n$ for some $n\in \N$, defined on the same probability space $(\Omega, \sF, P)$. The **conditional expectation of random variable $X$ given the random vector $Y$** is defined as $\E[X\mid Y] \triangleq \E[X\mid\sigma(Y)]$.
:::

::: lem
For a random sequence $X: \Omega \to \R^\N$ defined on the same probability space $(\Omega, \sF, P)$, we have
:::

::: proof
*Proof.* For any $x \in \R^{n+1}$, any generating event for collection $\sigma(X_1, \dots, X_n)$ is of the form $\cap_{i=1}^nX_i^{-1}(-\infty, x_i] = \cap_{i=1}^nX_i^{-1}(-\infty, x_i]\cap X_{n+1}^{-1}(\R)$, a generating event for collection $\sigma(X_1, \dots, X_{n+1})$. ◻
:::

# Properties of Conditional Expectation

::: prop
Let $X,Y$ be random variables on the probability space $(\Omega, \sF, P)$ such that $\E\abs{X} , \E\abs{Y} < \infty$. Let $\sG$ and $\sH$ be event spaces such that $\sG, \sH \subset \sF$. Then the following statements are true.

1.  **Identity:** If $X$ is $\sG$-measurable and $\E\abs{X} < \infty$, then $X = \E[X\mid\sG]$ a.s. In particular, $c = \E[c\mid \sG]$, for any constant $c \in  \R$.

2.  **Linearity:** $\E[(\alpha X + \beta Y) \mid \sG] = \alpha \E[X\mid\sG] + \beta E[Y\mid \sG]$ a.s.

3.  **Monotonicity:** If $X \le Y$ a.s., then $\E[X\mid\sG] \le E[Y\mid \sG]$ a.s.

4.  **Conditional Jensen's inequality:** If $\psi : \R \to  \R$ is convex and $\E\abs{\psi(X)} <\infty$, then $\psi(\E[X\mid\sG]) \le \E[\psi(X) \mid \sG]$ a.s.

5.  **Pulling out what's known:** If $Y$ is $\sG$-measurable and $\E\abs{XY} <\infty$, then $\E[XY\mid \sG] = Y\E[X\mid\sG]$ a.s.

6.  **Tower property:** If $\sH \subseteq \sG$, then $\E[\E[X\mid\sG]\mid \sH] = \E[X\mid \sH]$ a.s.

7.  **Irrelevance of independent information:** If $\sH$ is independent of $\sigma (\sG, \sigma (X))$ then $\E[X|\sigma (\sG, \sH)] = \E[X\mid\sG] \text{ a.s. }$ In particular, if $X$ is independent of $\sH$, then $\E[X\mid \sH] = \E[X]$ a.s.

8.  **$L^2$-projection:** If $\E\abs{X}^2 < \infty$, then $\zeta^\ast \triangleq \E[X\mid\sG]$ minimizes $\E[(X - \zeta)^2]$ over all $\sG$-measurable random variables $\zeta$ such that $\E\abs{\zeta}^2 < \infty$.
:::

::: proof
*Proof.* In all the properties below, we have to show that conditional expectation given an event space equals another random variable almost surely. To this end, we will show that the right hand side satisfies the three properties of the conditional expectation random variable, and hence is the conditional expectation from almost sure uniqueness.

1.  **Identity:** It follows from the definition that $X$ satisfies all three conditions for conditional expectation. The event space generated by any constant function is the trivial event space $\set{\emptyset, \Omega} \subseteq \sG$ for any event space. Hence, $\E[c\mid \sG] = c$.

2.  **Linearity:** Let $Z \triangleq \E[(\alpha X + \beta Y) \mid \sG]$ and $Z_1 \triangleq \E[X\mid\sG]$ and $Z_2\triangleq\E[Y\mid\sG]$. We have to show that $Z = \alpha Z_1+ \beta Z_2$ almost surely.

    (i) From the definition of conditional expectation, we have $\E[X\mid\sG], \E[Y\mid\sG]$ are $\sG$-measurable. In addition, the linear map $g: \R^2\to\R$ defined by $g(x) \triangleq \alpha x_1 + \beta x_2$ is Borel measurable. Therefore, the linear combination $\alpha Z_1 + \beta Z_2$ is $\sG$-measurable.

    (ii) For any $G \in \sG$, from the linearity of expectation and definition of conditional expectation, we have

    (iii) From the definition of conditional expectation, we have $\E\abs{Z_1}, \E\abs{Z_2}$ are finite. Therefore, we have

    This implies that $\alpha Z_1 + \beta Z_2$ satisfies three properties of conditional expectation $\E[(\alpha X +\beta Y)\mid\sG]$. From the almost sure uniqueness of conditional expectation, we have $Z = \alpha Z_1 + \beta Z_2$ almost surely.

3.  **Monotonicity:** Let $\epsilon > 0$ and define $A_\epsilon \triangleq \set{\E[X\mid\sG] - \E[Y\mid \sG] >\epsilon} \in  \sG$. Then from the definition of conditional expectation, we have Thus, we obtain that $P(A_\epsilon) = 0$ for all $\epsilon > 0$. Taking limit $\epsilon \downarrow 0$, we get

4.  **Conditional Jensen's inequality:** We will use the fact that a convex function can always be represented by the supremum of a family of affine functions. Accordingly, we will assume for a convex function $\psi:\R\to\R$, we have linear functions $\phi_i:\R\to\R$ and constants $c_i\in\R$ for all $i \in I$ such that $\psi = \sup_{i\in I}(\phi_i+c_i)$.

    For each $i\in I$, we have $\phi_i(\E[X\mid\sG])+c_i = \E[\phi_i(X)\mid\sG] +c_i\le \E[\psi(X)\mid\sG]$ from the linearity and monotonicity of conditional expectation. It follows that

5.  **Pulling out what's known:** From the almost sure uniqueness of conditional expectation, it suffices to show that $Y\E[X\mid\sG]$ satisfies following three properties of the conditional expectation $\E[XY\mid\sG]$:

    (i) the random variable $Y\E[X\mid\sG]$ is $\sG$-measurable,

    (ii) $\E[XY\Ind{G}] = \E[Y\E[X\mid\sG]\Ind{G}]$ for any event $G\in\sG$, and

    (iii) $\E\abs{Y\E[X\mid\sG]}$ is finite.

    Part (i) is true since $Y$ is given to be $\sG$-measurable, $\E[X\mid\sG]$ is $\sG$-measurable by the definition of conditional expectation, and product function is Borel measurable.

    It suffices to show part (ii) and (iii) for simple $\sG$-measurable random variables $Y=\sum_{y\in\sY}y\Ind{E_y}$ where $E_y = Y^{-1}\set{y} \in \sG$. For any $G\in\sG$, we have $G\cap E_y\in\sG$ for all $y \in \sY$ and $\cup_{y\in\sY}(G\cap E_y) = G$.

    Part (ii) follow from the linearity of expectation and definition of conditional expectation $\E[X\mid\sG]$, such that

    Part (iii) follows from the fact that $\E\abs{XY}$ is finite and the conditional Jensen's inequality applied to convex function $\abs{\cdot} : \R \to \R_+$ to get $\abs{\E[X\mid\sG]} \le \E[\abs{X}\mid\sG]$. Therefore,

6.  **Tower property:** From the almost sure uniqueness of conditional expectation, it suffices to show that

    (i) $\E[X\mid\sH]$ is $\sH$-measurable,

    (ii) $\E[\E[X\mid\sH]\Ind{H}] = \E[\E[X\mid\sG]\Ind{H}]$ for all $H\in\sH$, and

    (iii) $\E[\abs{\E[X\mid\sH]}]$ is finite.

    Part (i) follows from the definition of conditional expectation, which implies that $\E[X\mid \sH]$ is $\sH$ measurable.

    Part (ii) follows from the fact that $\sH \subseteq \sG$, and hence any $H \in \sH$ belongs to $\sG$. Therefore, from the definition of conditional expectation, we have

    Part (iii) follows from the conditional Jensen's inequality applied to convex function $\abs{\cdot}:\R\to\R_+$ to get $\abs{\E[X\mid\sH]} \le \E[\abs{X}\mid\sH]$, and hence $\E\abs{\E[X\mid\sH]} \le \E\abs{X} < \infty$.

7.  **Irrelevance of independent information:** From the almost sure uniqueness of conditional expectation, it suffices to show that

    (i) $\E[X\mid\sG]$ is $\sigma(\sG,\sH)$-measurable,

    (ii) $\E[\E[X\mid\sG]\Ind{G}] = \E[X\Ind{G}]$ for all $G\in\sigma(\sG,\sH)$, and

    (iii) $\E\abs{\E[X\mid\sG]}$ is finite.

    Part (i) follows from the definition of conditional expectation and the definition of $\sigma(\sG,\sH)$. Since $\E[X\mid\sG]$ is $\sG$-measurable, it is $\sigma(\sG,\sH)$ measurable.

    Part (ii) follows from the fact that it suffices to show for events $A = G \cap H \in \sigma(\sG,\sH)$ where $G \in \sG$ and $H \in \sH$. In this case,

    Part (iii) follows from the conditional Jensen's inequality applied to convex function $\abs{\cdot}:\R\to\R_+$ to get $\abs{\E[X\mid\sG]} \le \E[\abs{X}\mid\sG]$. This implies that $\E\abs{\E[X\mid\sG]} \le \E\abs{X} < \infty$.

8.  **$L^2$-projection:** We define $L^2(\sG) \triangleq \set{\zeta \text{ a } \sG \text{ measurable random variable}: 
    \E\zeta^2 < \infty%,\zeta^{-1}(-\infty, x] \in \sG \text{ for all }x\in \R
    }$. From the conditional Jensen's inequality applied to convex function $(\cdot)^2:\R \to \R_+$, we get that $(\E[X\mid\sG])^2 \le \E[X^2\mid\sG]$ a.s.. Since $X\in L^2$, it follows that $X^2\in L^1$ and hence $\E[X\mid\sG] \in L^2$. It follows that $\zeta^\ast \triangleq \E[X\mid\sG] \in L^2(\sG)$ from the definition of conditional expectation.

    We first show that $X - \zeta^\ast$ is uncorrelated with all $\zeta \in L^2(\sG)$. Towards this end, we let $\zeta\in L^2(\sG)$ and observe that The above equality follows from the linearity of expectation, the $\sG$-measurability of $\zeta$, and the definition of conditional expectation. Since $\zeta^\ast\in L^2(\sG)$, we have $(\zeta-\zeta^\ast)\in L^2(\sG)$. Therefore, $\E[(X - \zeta^\ast)(\zeta-\zeta^\ast)] = 0$.

    For any $\zeta\in L^2(\sG)$, we can write from the linearity of expectation

 ◻
:::
