---
title: "Lecture-24: Poisson Point Processes"
author: "Parimal Parag"
---

# Simple point processes

Consider the $d$-dimensional Euclidean space $\R^d$. The collection of Borel measurable subsets $\sB(\R^d)$ of the above Euclidean space is generated by sets $B(x) \triangleq \set{y \in \R^d: y_i \le x_i}$ for $x \in \R^d$.

::: defn
A **simple point process** is a random countable collection of *distinct points* $S: \Omega \to \sX^\N$, such that the distance $\norm{S_n} \to \infty$ as $n \to \infty$.
:::

::: rem
Since $S$ is a simple point process, each point $S_n$ is unique. Therefore, we can identify $S$ as a random set of points in $\sX$ and $S\cap A$ is the random set of points in $A$.
:::

::: rem
For any simple point process $S$, we have $P(\set{S_n = S_m \text{ for any } n \neq m}) = 0$ and $\abs{S\cap A}$ is finite almost surely for any bounded set $A \in \sB(\sX)$.
:::

:::: shaded
::: exmp
We can simplify this definition for $d=1$. When $\sX = \R_+$, one can order the points of the process $S: \Omega \to \R_+^\N$ to get ordered process $\tilde{S}: \Omega \to \R_+^\N$, such that $\tilde{S}_n = S_{(n)}$ is the $n$th order statistics of $S$. That is, $S_{(0)} \triangleq 0$, and $S_{(n)} \triangleq \inf\set{S_k > S_{(n-1)}: k \in \N}.$ such that $S_{(1)} < S_{(2)} < \dots < S_{(n)} < \dots$, and $\lim_{n \in \N}S_{(n)} = \infty$. We will call this an arrival process.
:::
::::

::: defn
Corresponding to a point process $S:\Omega\to\sX^\N$, we denote the number of points in a set $A \in \sB(\sX)$ by The resulting process $N: \Omega \to {\Z_+}^ {\sB(\sX)}$ is called a **counting process** for the point process $S: \Omega \to \sX^\N$.
:::

::: rem
Let $A \in \sB(\sX)^k$ be a bounded partition of $B\in \sB(\sX)$. From the disjointness of $(A_1, \dots, A_k)$, we have
:::

::: defn
A counting process is **simple** if the underlying point process is simple.
:::

::: rem
For a simple counting process $N$, we have $N(\set{x}) \le 1$ almost surely for all $x \in \sX$.
:::

::: rem
Let $N : \Omega \to {\Z_+}^{\sB(\sX)}$ be the counting process for the point process $S: \Omega \to \sX^\N$.

1.  Note that the point process $S$ and the counting process $N$ carry the same information.

2.  The distribution of point process $S$ is completely characterized by the finite dimensional distributions of random vectors $(N(A_1), \dots, N(A_k))$ for any bounded sets $A_1, \dots, A_k \in \sB(\sX)$ and finite $k \in \N$.
:::

:::: shaded
::: exmp
Since the Borel measurable sets $\sB(\R_+)$ are generated by half-open intervals $\set{(0,t]: t \in \R_+}$, we denote the counting process by $N: \Omega \to {\Z_+}^{\R_+}$, where $N_t \triangleq N(0, t]= \sum_{n \in \N}\SetIn{S_n \in (0,t]}$ is the number of points in the half-open interval $(0,t]$. For $s < t$, the number of points in interval $(s,t]$ is $N(s,t] = N(0,t] - N(0,s] = N_t - N_s$.
:::
::::

::: thm
[]{#thm:void label="thm:void"} Distribution of a simple point process $S:\Omega\to\sX^\N$ on a locally compact second countable space $\sX$ is completely determined by void probabilities $(P\set{N(A)=0}: A \in \sB(\sX))$.
:::

::: proof
*Proof.* It suffices to show that the finite dimensional distributions of $S$ on locally compact sets are characterized by void probabilities.

1.  We will show this by induction on the number of points $k$ in a bounded set $A \in \sB$. Let $A_1, \dots, A_k, B \in \sB(\sX)$ locally compact, then we will show that $u_k \triangleq P(\cap_{i=1}^k\set{N(A_i)> 0}\cap\set{N(B) = 0})$ can be computed from void probabilities. From $k=1$, we have The induction can be proved by the recursive relation

2.  For any locally compact set $B \in \sB(\sX)$, there exists a sequence of nested partitions $B_n \triangleq (B_{n,j}: j \in [J_n])$ that eventually separates the points in $S\cap B$ as $n \to \infty$. We define the number of subsets of partition $(B_{n,j}: j \in [J_n])$ that consist of at least one point in $S\cap B$, as $H_n(B) \triangleq \sum_{j=1}^{J_n}\SetIn{N(B_{n,j}) > 0}$ where $H_n(B) \uparrow N(B)$ almost surely.

3.  We next show that for all locally compact sets $B_1, \dots, B_k \in \sB(\sX)$ and $j_1, \dots, j_k \in \N$, the probability $P(\cap_{i=1}^k\set{H_n(B_i) = j_i})$ can be expressed in terms of void probabilities. We observe that This can be expressed in terms of void probabilities by Step 1.

4.  For a simple point process, we have the following almost sure limit $\lim_n\cap_{i=1}^k\set{H_n(B_i) = j_i} = \cap_{i=1}^k\set{N(B_i) = j_i}$. The result follows from the continuity of probability.

 ◻
:::

::: rem
Recall that $\abs{A} = \int_{x \in A}dx$ is the volume of the set $A \in \sB(\R^d)$ and for any such $A$.
:::

::: defn
The **intensity measure** $\Lambda:\sB(\sX)\to\R_+$ is defined for each bounded set $A \in \sX$ as its scaled volume in terms of the **intensity density** $\lambda: \R^d \to \R_+$, as If the intensity density $\lambda(x) = \lambda$ for all $x \in \R^d$, then $\Lambda(A) = \lambda\abs{A}$. In particular for partition $A_1, \dots, A_k$ for a set $B$, we have $\Lambda(B) = \sum_{i=1}^k\Lambda(A_i)$.
:::

# Poisson point process

::: defn
A non-negative integer valued random variable $N: \Omega \to \Z_+$ is called **Poisson** if for some constant $\lambda > 0$, we have
:::

::: rem
It is easy to check that $\E N = \Var[N] = \lambda$. Furthermore, the moment generating function $M_{N_t} = \E e^{t N} = e^{\lambda(e^{t} - 1)}$ exists for all $t \in \R$.
:::

::: cor
[]{#cor:ExpPoisson label="cor:ExpPoisson"} A simple counting process $N: \Omega \to \Z_+^{\sB(\sX)}$ has Poisson marginal distribution with intensity measure $\Lambda:\sB(\sX)\to\R_+$ if and only if void probabilities are exponential with the same intensity measure $\Lambda$.
:::

::: proof
*Proof.* It is clear that if the marginal distribution of the counting process $N$ is Poisson with intensity measure $\Lambda$, then the void probability $P\set{N(A) = 0} = e^{-\Lambda(A)}$ is exponential for any bounded set $A \in \sB(\sX)$.

Conversely, we assume that the void probabilities are exponentially distributed with intensity measure $\Lambda$. It follows from the linearity of intensity measure that for any finite, bounded, and disjoint sets $B_1, \dots, B_k \in \sB(\sX)$, we have That is, the Bernoulli random vector $(\SetIn{N(B_i) = 0}: i \in [k])$ is independent for any finite $k \in \N$ and bounded disjoint $\sB(\sX)$ measurable sets $B_1, \dots, B_k$. Next we consider a set $B \in \sB(\sX)$ and a partition $B_n \triangleq (B_{n,j}: j \in [J_n])$ of $B$ such that $\Lambda(B_{n,j}) = \frac{\Lambda(B)}{J_n}$ for all $j \in [J_n]$. It follows that $H_n(B) \triangleq \sum_{j=1}^{J_n}\SetIn{N(B_{n,j})> 0}$ is the sum of $J_n$ Bernoulli random variables with success probability $p_n \triangleq 1-e^{-\Lambda(B)/J_n}$, and hence has a Binomial distribution with parameters $(J_n, p_n)$. Therefore, Recall that $H_n(B) \uparrow N(B)$ as $n\to\infty$ in the proof of Rényi's Theorem, and $\lim_{n\to\infty}J_n = \infty$ and $\lim_{n\in\N}\abs{B_{n,j}}= 0$. Thus, $\lim_{n\to\infty}\frac{J_n!}{(J_n-m)!}(e^{\Lambda(B)/J_n}-1)^m = \Lambda(B)^m$. Taking limit $n\to\infty$ on both sides of the above equation, we get the result. ◻
:::

::: defn
A counting process $N:\Omega\to\Z_+^{\sB(\sX)}$ has the **completely independence property**, if for any collection of finite disjoint and bounded sets $A_1, \dots, A_k \in \sB(\sX)$, the vector $(N(A_1), \dots, N(A_k)):\Omega \to \Z_+^k$ is independent. That is,
:::

::: defn
A simple point process $S: \Omega \to \sX^\N$ is **Poisson point process**, if the associated counting process $N: \Omega \to \Z_+^{\sB(\sX)}$ has complete independence property and the marginal distributions are Poisson.
:::

::: defn
The **intensity measure** $\Lambda: \sB(\sX) \to \R_+$ of Poisson process $S$ is defined by $\Lambda(A) \triangleq \E N(A)$ for all bounded $A \in \sB(\sX)$.
:::

::: rem
Recall that for any partition $A \in \sB(\sX)^k$ of a bounded set $B \in \sB(\sX)$, we have $N(B) = \sum_{i=1}^kN(A_i)$ and therefore it follows from the linearity of expectations that $\Lambda(B) = \E N(B) = \sum_{i=1}^k\E N(A_i) = \sum_{i=1}^k\Lambda(A_i).$ Thus, this is a valid intensity measure.
:::

::: rem
For a Poisson process with intensity measure $\Lambda$, it follows from the definition that for any finite $k \in \Z_+$, and bounded mutually disjoint sets $A_1, \dots, A_k \in \sB(\sX)$, we have
:::

::: defn
If the intensity measure $\Lambda$ of a Poisson process $S$ satisfies $\Lambda(A) = \lambda\abs{A}$ for all bounded $A \in \sB(\sX)$, then we call $S$ a **homogeneous Poisson point process** and $\lambda$ is its intensity.
:::

# Equivalent characterizations

::: thm
[]{#thm:equiv label="thm:equiv"} Following are equivalent for a simple counting process $N: \Omega \to {\Z_+}^{\sB(\sX)}$.

1.  Process $N$ is Poisson with locally finite intensity measure $\Lambda$.

2.  For each bounded $A \in \sB(\sX)$, we have $P\set{N(A) = 0} = e^{-\Lambda(A)}$.

3.  For each bounded $A \in \sB(\sX)$, the number of points $N(A)$ is a Poisson with parameter $\Lambda(A)$.

4.  Process $N$ has the completely independence property, and $\E N(A) = \Lambda(A)$ for all bounded sets $A \in \sB(\sX)$.
:::

::: proof
*Proof.* We will show that $i\_ \implies ii\_ \implies iii\_ \implies iv\_ \implies i\_$.

1.  It follows from the definition of Poisson point processes and definition of Poisson random variables.

2.  From Corollary [\[cor:ExpPoisson\]](#cor:ExpPoisson){reference-type="ref" reference="cor:ExpPoisson"}, we know that if void probabilities are exponential, then the marginal distributions are Poisson.

3.  We will show this in two steps.

    - Since the distribution of random variable $N(A)$ is Poisson, it has mean $\E N(A) = \Lambda(A)$.

    - Consider a partition $A \in \sB^k$ for a bounded set $B\in\sB(\sX)$, then $\Lambda(B) = \Lambda(A_1) + \dots + \Lambda(A_k)$. Consider all partitions $n\in\Z_+^k$ of a non-negative integer $m \in \Z_+$, to write Using the definition of Poisson distribution, we can write the LHS of the above equation as Since the expansion of $(a_1 + \dots + a_k)^m = \sum_{n_1 + \dots+n_k = m}\binom{m}{n_1, \dots, n_k}\prod_{i=1}^ka_i^{n_i}$, we get Equating each term in the summation, we get $P\set{N(A_1) = n_1, \dots, N(A_k) = n_k} = \prod_{i=1}^kP\set{N(A_i) = n_i}$.

4.  From Corollary [\[cor:ExpPoisson\]](#cor:ExpPoisson){reference-type="ref" reference="cor:ExpPoisson"}, if the void probability is exponential with intensity measure $\Lambda$, then the marginal distribution if Poisson with the same intensity measure. We define $f:\sB(\sX)\to(-\infty, 0]$ by $f(A) \triangleq \ln P\set{N(A) = 0}$ for all bounded $A \in \sB(\sX)$. Then, we observe that for any partition $(A_1,\dots, A_k)$ of $A$, we have $f(\cup_{i=1}^kA_i) = \ln P\set{N(A)= 0} = \ln\prod_{i=1}^kP\set{N(A_i) = 0} = \sum_{i=1}^kf(A_i)$. It follows that $-f:\sB(\sX)\to\R_+$ is an intensity measure, and $P\set{N(A)=0} = e^{f(A)}$. Since $\E N(A) = -f(A) = \Lambda(A)$, the result follows.

 ◻
:::

::: cor
A random process $N: \Omega \to \Z_+^{\R_+}$ indexed by time $t \in \Z_+$ is the counting process associated with a one-dimensional Poisson process $S: \Omega \to \R_+^\N$ having intensity measure $\Lambda$ iff

(a) Starting with $N_0 = 0$, the process $N_t$ takes a non-negative integer value for all $t \in \R_+$;

(b) the increment $N_s - N_t$ is surely nonnegative for any $s \ge t$;

(c) the increments $N_{t_1}, N_{t_2} - N_{t_1},  \dots , N_{t_n} - N_{t_{n-1}}$ are *independent* for any $0 < t_1 < t_2 < \dots < t_{n-1} < t_n$;

(d) the increment $N_s - N_t$ is distributed as Poisson random variable with parameter $\Lambda(t, s]$ for $s \ge t$.

The Poisson process is homogeneous with intensity $\lambda$, iff in addition to conditions $(a), (b), (c)$, the distribution of the increment $N_{t+s} - N_t$ depends on the value $s \in \R_+$ but is independent of $t \in \R_+$. That, is the increments are *stationary*.
:::

::: proof
*Proof.* We have already seen that definition of Poisson processes implies all four conditions. Conditions $(a)$ and $(b)$ imply that $N$ is a simple counting process on the half-line, condition $(c)$ is the complete independence property of the point process, and condition $(d)$ provides the intensity measure. The result follows from the equivalence $iv\_$ in Theorem [\[thm:equiv\]](#thm:equiv){reference-type="ref" reference="thm:equiv"}. ◻
:::
