---
title: "Compound Poisson Processes"
author: "Parimal Parag"
format:
  html:
    mathjax:
      fonts: STIX-Web
    toc: true
    toc-depth: 2
    number-sections: false
---

# Compound Poisson process

::: defn
**Definition 1**. A **compound Poisson process** is a real-valued right-continuous process $Z:\Omega\to\R_+^{\R_+}$ with the following properties.

1.  **Finitely many jumps:** for all $\omega \in \Omega$, sample path $t \mapsto Z_t(\omega)$ has finitely many jumps in finite intervals,

2.  **Independent increments:** for all $t,s \ge 0$; increments $Z_{t+s}-Z_t$ is independent of past $\sF_t \triangleq \sigma(Z_u: u\le t)$,

3.  **Stationary increments:** for all $t,s \ge 0$, distribution of $Z_{t+s}-Z_t$ depends only on $s$ and not on $t$.
:::

::: defn
For each $\omega \in \Omega$ and $n \in \N$, we can define time and size of $n$th jump
:::

::: rem
**Remark 1**. Recall that $\sF_s = \sigma(Z_u, u \in (0, s])$ is the collection of historical events until time $s$ associated with the process $Z$. If $\tS_n$ is almost surely finite for all $n \in \N$, then the sequence of jump times $\tS:\Omega\to\R_+^\N$ is a sequence of stopping times with respect to the natural filtration $\sF_\bullet$ of the process $Z$.
:::

::: rem
**Remark 2**. Let $N:\Omega\to\Z_+^{\R_+}$ be the simple counting process associated with the number of jumps of compound Poisson process $Z$ in $(0,t]$ defined by $N_t \triangleq \sum_{n\in\N}\SetIn{\tS_n\le t}$ for all $t\in\R_+$. Then, $\tS_n$ and $Y_n$ are the respectively the arrival instant and the size of the $n$th jump, and we can write $Z_t = \sum_{i = 1}^{N_t}Y_i$.
:::

::: prop
**Proposition 2**. A stochastic process $Z:\Omega\to\R_+^{\R_+}$ is a compound Poisson process iff its jump times form a Poisson process and the jump sizes form an random sequence independent of the jump times.
:::

::: proof
*Proof.* We will prove it in two steps.

- Let $Z$ be a compound Poisson process with the jump instant sequence $\tS:\Omega\to\R_+^\N$ and the jump size sequence $Y:\Omega\to\R_+^\N$. We will show that the counting process $N:\Omega\to\Z_+^{\R_+}$ is simple and has stationary and independent increments and the jump size sequence $Y$ is .

  - From the definition of jump instant sequence $\tS$, it follows that the counting process $N$ is adapted to the natural filtration $\sF_\bullet$ of the compound Poisson process $Z$. Since $Z_{t+s} - Z_t = \sum_{i = N_t+1}^{N_{t+s}}Y_i$, and the compound Poisson processes have independent increments, it follows that the increment $(N_{t+s}-N_t: s \ge 0)$ and $(Y_{N_t+j}: j \in \N)$ are independent of the past $\sF_t$.

  - Let's assume that step sizes are positive, then we have From the stationarity of the increments it follows that the probability $P\set{N_{t+s}-N_t = 0}$ is independent of $t$ and equal to $e^{-\lambda s}$ for some $\lambda \in \R_+$. It follows that the counting process $N:\Omega\to\Z_+^{\R_+}$ has stationary increments and the associated jump sequence $\tS$ is homogeneous Poisson with intensity density $\lambda$.

  - The compound Poisson process has the Markov property from stationary and independent increment property. Further, since each sample path $t \mapsto Z_t$ is right continuous, the process satisfies the strong Markov property at each almost sure stopping time.

  - We will inductively show that $\tS:\Omega\to\R_+^\N$ is a stopping time sequence and hence the inter jump times sequence $X:\Omega\to\R_+^\N$ defined by $X_n \triangleq \tS_n-\tS_{n-1}$ for each $n\in\N$ is an sequence. From the exponential distribution of $\tS_1$, it follows that it is almost surely finite and hence a stopping time. From the stationary of increments of compound Poisson process and the strong Markov property at stopping times $\tS_2 -\tS_1 = \tS_1$ is independent of $\sF_{\tS_1}$ and identical in distribution to $\tS_1$. The result follows inductively.

  - From strong Markov property of $Z$, the jump size $Y_n$ is independent of the past $\sF_{\tS_{n-1}} = \sigma(Z_u: u \le \tS_{n-1})$ and from stationarity it is identically distributed to $Y_1$ for each $n \in \N$. It follows that the jump size sequence $Y$ is and independent of jump instant sequence $\tS$.

  - Similar arguments can be used to show for negative jump sizes. For real jump sizes, we can form two independent Poisson processes with negative and positive jumps, and the superposition of these two processes is Poisson.

- Let $X:\Omega\to\R_+^\N$ be an inter-jump sequence distributed exponentially with rate $\lambda$ and $Y:\Omega\to\R^\N$ be an jump size sequence independent of $X$. We can define the jump instant sequence $\tS:\Omega\to\R_+^\N$ defined as $\tS_n \triangleq \sum_{i=1}^nX_i$ for each $n\in\N$, the counting process for the number of jumps $N:\Omega\to\Z_+^{\R_+}$ defined as $N_t \triangleq \sum_{n\in\N}\SetIn{\tS_n \le t}$ for each $t\in\R_+$, and the compound process $Z:\Omega\to\R^{\R_+}$ defined as $Z_t \triangleq \sum_{n =1}^{N_t}Y_n$ for each $t\in\R_+$.

  - Since $N_t$ is finite for any finite $t$, it follows that the compound Poisson process $Z$ has finitely many jumps in finite intervals.

  - For any finite $n \in \N$ and finite intervals $I_i$ for $i \in [n]$, we can write $Z(I_i)= \sum_{k=1}^{N(I_i)}Y_{ik}$, where $Y_{ik}$ denotes the $k$th jump size in the interval $I_i$. Since the independent sequence $(N(I_i): i \in [n])$ and $Y:\Omega\to\R_+^\N$ are also mutually independent, it follows that $Z(I_i)$ are independent.

  - Further, the stationarity of the increments of the compound process is inferred from the distribution of $Z(I_i)$, which is

 ◻
:::

:::: shaded*
::: exmp
**Example 3**. Examples of compound Poisson processes.

- Arrival of customers in a store is a Poison process $N$. Each customer $i$ spends an amount $X_i$ independent of the arrival process. Now define $Z_t \triangleq Y_{N_t}$ as the amount spent by the customers arriving until time $t \in \R_+$. Then $Z:\Omega\to\R_+^{\R_+}$ is a compound Poisson Process.

- Let the time between successive failures of a machine be independent and exponentially distributed. The cost of repair is random at each failure. Then the total cost of repair in a certain time $t$ is a compound Poisson Process.
:::
::::
