---
title: "Poisson processes: Conditional distribution"
author: "Parimal Parag"
format:
  html:
    mathjax:
      fonts: STIX-Web
    toc: true
    toc-depth: 2
    number-sections: false
---

# Joint conditional distribution of points in a finite window

Let $\sX =\R^d$ be a $d$-dimensional Euclidean space, and $S:\Omega\to\sX^\N$ be a Poisson point process with intensity measure $\Lambda: \sB(\sX) \to \R_+$ and associated counting process $N:\Omega\to\Z_+^{\sB(\sX)}$.

::: prop
Let $k \in \N$ be any positive integer. Consider a Poisson point process $S: \Omega \to \sX^\N$ with intensity measure $\Lambda:\sB(\sX)\to\R_+$, a finite partition $A\in \sB(\sX)^k$ that partitions a bounded set $B \in \sB(\sX)$, and a vector $n \in \Z_+^k$ that partitions a non negative integer $m \in \Z_+$. Then,
:::

::: proof
*Proof.* From the definition of conditional probability and the fact that $\cap_{i=1}^k\set{N(A_i) = n_i} \subseteq \set{N(B) =m}$, we can write the conditional probability on LHS as the ratio $$\begin{equation*}
%P(\set{N(A_1) = n_1, \dots, N(A_k) = n_k}\given\set{N(A) = n}) = 
\frac{P\set{N(A_1) = n_1, \dots, N(A_k) = n_k, N(B) = m}}{P\set{N(B) = m}} = 
\frac{P\set{N(A_1) = n_1, \dots, N(A_k) = n_k}}{P\set{N(B) = m}}.
\end{equation*}$$ From the complete independence property and Poisson marginals for the joint distribution of $(N(A_1), \dots, N(A_k))$ for the partition $A \in \sB(\sX)^k$, and the fact that the intensity measure sums over disjoint sets, i.e. $\Lambda(B) = \sum_{i=1}^k\Lambda(A_i)$, we can rewrite the RHS of the above equation as $$\begin{equation*}
\frac{P\set{N(A_1) = n_1, \dots, N(A_k) = n_k}}{P\set{N(B) = m}}
= \frac{\prod_{i=1}^ke^{-\Lambda(A_i)}\frac{\Lambda(A_i)^{n_i}}{n_i!}}{e^{-\Lambda(B)}\frac{\Lambda(B)^m}{m!}}
= \binom{m}{n_1, \dots, n_k}\prod_{i=1}^k\left(\frac{\Lambda(A_i)}{\Lambda(B)}\right)^{n_i}.
\end{equation*}$$ ◻
:::

::: rem
Consider a Poisson point process $S:\Omega\to\sX^\N$ with intensity measure $\Lambda: \sB(\sX) \to \R_+$ and counting process $N:\Omega\to\Z_+^{\sB(\sX)}$. Let $A \in \sB(\sX)^k$ be a partition for bounded set $B \in \sB(\sX)$.

1.  Defining $p_i \triangleq \frac{\Lambda(A_i)}{\Lambda(B)}$, we see that $(p_1, \dots, p_k) \in \cM([k])$ is a probability distribution. We also observe that When $N(B)=1$, we can call the point of $S$ in $B$ as $S_1$ without any loss of generality. That is, if we call $\set{S_1} = S \cap B$, then we have Similarly, when $N(B) = n_i$, we call the points of $S$ in $B$ as $S_1, \dots, S_{n_i}$ and denote $S\cap B = \set{S_1, \dots, S_{n_i}}$. For this case, we observe

2.  We can rewrite the Equation [\[eqn:multi\]](#eqn:multi){reference-type="eqref" reference="eqn:multi"} as a multinomial distribution, where

3.  For any finite set $F\subseteq \N$ of size $m \in \Z_+$ and $n\in\Z_+^k$ a partition of $m$, we define $\cP_k(F, n)$ to be the collection of all $k$-partitions $E \in \cP(\N)^k$ of $F$ such that $\abs{E_i} = n_i$ for $i \in [k]$. Then, the multinomial coefficient accounts for number of partitions of $m$ points into sets with $n_1,  \dots, n_k$ points. That is,

4.  Recall that the event $\set{N(A_i) = n_i} = \set{\abs{S \cap A_i} = n_i}$. Hence, we can write

5.  When $N(B) = m$, we denote $S\cap B$ by $F = \set{S_1, \dots, S_m}$ without any loss of generality. We further observe that when $N(A_i) = n_i$ for all $i \in [k]$, then $(S \cap A_1, \dots, S \cap A_k) \in \cP_k(S\cap B,n)$. Therefore, we can re-write the event That is, we can write the conditional probability conditioned on $S\cap B = F$, as

6.  Equating the RHS of the above equation term-wise, we obtain that conditioned on each of these points falling inside the window $B$, the conditional probability of each point falling in partition $A_i$ is independent of all other points and given by $p_i$. That is, we have It means that given $m$ points in the window $B$, the location of these points are independently and identically distributed in $B$ according to the distribution $\frac{\Lambda(\cdot)}{\Lambda(B)}$.

7.  If the Poisson process is homogeneous, the distribution is uniform over the window $B$.

8.  For a Poisson process with intensity measure $\Lambda$ and any bounded set $A \in \sB$, the number of points $N(A)$ in the set $A$ is a Poisson random variable with parameter $\Lambda(A)$. Given the number of points $N(A)$, the location of all the points in $S\cap A$ are with density $\frac{\lambda(x)}{\Lambda(A)}$ for all $x \in A$.
:::

:::: shaded
::: rem
If we are interested in simulating a two dimensional homogeneous Poisson point process with density $\lambda$ in a uniform square $A = [0,1]\times[0,1]$. Then, we first generate the random variable $N(A):\Omega\to\Z_+$ that takes value $n$ with probability $e^{-\lambda}\frac{\lambda^n}{n!}$. Next, for each of the $N(A)=n$ points, we generate the location $(X_i, Y_i) \in \R^2$ uniformly at random. That is, $X:\Omega\to[0,1]^n$ and $Y:\Omega\to[0,1]^n$ are independent uniform sequences.
:::
::::

::: cor
For a homogeneous Poisson point process on the half-line with ordered set of points $\tilde{S} = (S_{(n)} \in \R_+: n \in \N)$, we can write the conditional density of ordered points $(S_{(1)}, \dots, S_{(k)})$ given the event $\set{N_t = k}$ as the ordered statistics of uniformly distributed random variables. Specifically, we have
:::

::: proof
*Proof.* Given $\set{N_t = k}$, we can denote the points of the Poisson process in $(0,t]$ by $S_1, \dots, S_k$. From the above remark, we know that $S_1, \dots, S_k$ are uniform in $(0, t]$, conditioned on the number of points $N_t = k$. Hence, we can write Therefore, for $0 < t_1 < \dots < t_k < 1$ and $(h_1, \dots, h_k)$ sufficiently small, we have Since $(S_1, \dots, S_k)$ are conditionally independent given $S\cap A = \set{S_1, \dots, S_k}$, it follows that any permutation $\sigma: [k] \to [k]$, the conditional joint distribution of $(S_{\sigma(1)}, \dots, S_{\sigma(k)})$ is identical to that of $(S_1, \dots, S_k)$ given $S\cap A = \set{S_1, \dots, S_k}$. Further, we observe that the order statistics of $(S_{\sigma(1)}, \dots, S_{\sigma(k)})$ is identical to that of $(S_{1}, \dots, S_{k})$. Therefore, we can write the following equality for the events The result follows since the number of permutations $\sigma: [k] \to [k]$ is $k!$. ◻
:::
