---
title: "Random Processes"
author: "Parimal Parag"
format:
  html:
    mathjax:
      fonts: STIX-Web
    toc: true
    toc-depth: 2
    number-sections: false
---

# Introduction

::: rem
**Remark 1**. For an arbitrary index set $T$, and a real-valued function $x \in \R^T$, the projection operator $\pi_t:\R^T\to\R$ maps $x\in\R^T$ to $\pi_t(x) = x_t$.
:::

::: defn
**Definition 1** (Random process). Let $(\Omega, \sF, P)$ be a probability space. For an arbitrary index set $T$ and state space $\sX \subseteq \R$, a map $X : \Omega \to \sX^T$ is called a **random process** if the projections $X_t:\Omega\to\sX$ defined by $\omega \mapsto X_t(\omega) \triangleq (\pi_t\circ X)(\omega)$ are random variables on the given probability space.
:::

::: defn
**Definition 2**. For each outcome $\omega \in \Omega$, we have a function $X(\omega): T \mapsto \sX$ called the **sample path** or the **sample function** of the process $X$.
:::

::: rem
**Remark 2**. A random process $X$ defined on probability space $(\Omega, \sF, P)$ with index set $T$ and state space $\sX\subseteq\R$, can be thought of as

(a) a map $X: \Omega \times T \to \sX$,

(b) a map $X: T \to \sX^\Omega$, i.e. a collection of random variables $X_t: \Omega \to \sX$ for each time $t \in T$,

(c) a map $X: \Omega \to \sX^T$, i.e. a collection of sample functions $X(\omega): T \to \sX$ for each random outcome $\omega \in \Omega$.
:::

## Classification

State space $\sX$ can be countable or uncountable, corresponding to discrete or continuous valued process. If the index set $T \subseteq \R$ is countable, the stochastic process is called **discrete**-time stochastic process or random sequence. When the index set $T$ is uncountable, it is called **continuous**-time stochastic process. The index set $T$ doesn't have to be time, if the index set is space, and then the stochastic process is spatial process. When $T = \R^n \times [0, \infty)$, stochastic process $X$ is a spatio-temporal process.

:::: shaded
::: exmp
**Example 3**. We list some examples of each such stochastic process.

1.  Discrete random sequence: brand switching, discrete time queues, number of people at bank each day.

2.  Continuous random sequence: stock prices, currency exchange rates, waiting time in queue of $n$th arrival, workload at arrivals in time sharing computer systems.

3.  Discrete random process: counting processes, population sampled at birth-death instants, number of people in queues.

4.  Continuous random process: water level in a dam, waiting time till service in a queue, location of a mobile node in a network.
:::
::::

## Measurability

For random process $X:\Omega\to \sX^T$ defined on the probability space $(\Omega, \sF, P)$, the projections $X_t \triangleq \pi_t\circ X$ are $\sF$-measurable random variables. Therefore, the set of outcomes $A_{X_t}(x) \triangleq X_t^{-1}(-\infty, x] \in \sF$ for all $t \in T$ and $x \in \R$.

::: defn
**Definition 4**. A random map $X:\Omega\to\sX^T$ is called $\sF$-**measurable** and hence a random process, if the set of outcomes $A_{X_t}(x) = X_t^{-1}(-\infty, x]\in \sF$ for all $t \in T$ and $x\in \R$.
:::

::: defn
**Definition 5**. The **event space generated by a random process** $X: \Omega\to\sX^T$ defined on a probability space $(\Omega,\sF,P)$ is given by
:::

::: defn
**Definition 6**. For a random process $X:\Omega \to \sX^T$ defined on the probability space $(\Omega,\sF,P)$, we define the projection of $X$ onto components $S \subseteq T$ as the random vector $X_S: \Omega \to \sX^S$, where $X_S \triangleq (X_s: s \in S)$.
:::

::: rem
**Remark 3**. Recall that $\pi_t^{-1}(-\infty, x] = \bigtimes_{s \in T}(-\infty, x_s]$ where $x_s = x$ for $s = t$ and $x_s = \infty$ for all $s\neq t$. The $\sF$-measurability of process $X$ implies that for any countable set $S \subseteq T$, we have $A_{X_S}(x_S) \triangleq \cap_{s \in S}A_{X_s}(x_s) \in \sF$ for $x_S \in \sX^S$.
:::

::: rem
**Remark 4**. We can define $A_X(x) \triangleq \cap_{t \in T}A_{X_t}(x_t)$ for any $x \in \R^T$. However, $A_X(x)$ is guaranteed to be an event only when $S \triangleq \set{t \in T: \pi_t(x) < \infty}$ is a countable set. In this case,
:::

:::: shaded
::: exmp
**Example 7** (Bernoulli sequence). []{#exmp:BernoulliSeqDefn label="exmp:BernoulliSeqDefn"} Consider a sample space $\set{H,T}^\N$. We define a mapping $X: \Omega \to \set{0,1}^\N$ such that $X_n(\omega) = \SetIn{H}(\omega_n) = \SetIn{\omega_n = H}$. The map $X$ is an $\sF$-measurable random sequence, if each $X_n: \Omega \to \set{0,1}$ is a bi-variate $\sF$-measurable random variable on the probability space $(\Omega,\sF,P)$. Therefore, the event space $\sF$ must contain the event space generated by sequence of events $E\in\sF^\N$ defined by $E_n \triangleq \set{\omega \in \Omega: X_n(\omega)=1} = \set{\omega \in \Omega: \omega_n = H} \in \sF$ for all $n\in \N$. That is,
:::
::::

## Distribution

::: defn
**Definition 8**. For a random process $X: \Omega \to \sX^T$ defined on the probability space $(\Omega,\sF, P)$, we define a **finite dimensional distribution** $F_{X_S}: \R^S \to [0,1]$ for a finite $S \subseteq T$ by
:::

:::: shaded
::: exmp
**Example 9**. Consider a probability space $(\Omega,\sF, P)$ defined by the sample space $\Omega = \set{H,T}^\N$, the event space $\sF \triangleq \sigma(E)$ where $E_n = \set{\omega \in \Omega: \omega_n = H}$ for $n\in\N$, and the probability measure $P: \sF \to [0,1]$ defined by Let $X: \Omega\to\set{0,1}^\N$ defined as $X_n(\omega) = \Ind{E_n}(\omega)$ for all outcomes $\omega \in \Omega$ and $n \in \N$. For this random sequence, we can obtain the finite dimensional distribution $F_{X_S}: \R^S \to [0,1]$ for any finite $S \subseteq T$ and $x \in \R^S$ in terms of $I_0(x) \triangleq \set{i \in S: x_i < 0}$ and $I_1(x) \triangleq \set{i \in S: x_i \in [0,1)}$, as
:::
::::

To define a measure on a random process, we can either put a measure on subsets of sample paths $(X(\omega) \in \R^T: \omega \in \Omega)$, or equip the collection of random variables $(X_t \in \R^\Omega: t \in T)$ with a joint measure. Either way, we are interested in identifying the joint distribution $F: \R^T \to [0,1]$. To this end, for any $x \in \R^T$, we need to know First of all, we don't know whether $A_X(x)$ is an event when $T$ is uncountable. Though, we can verify that $A_X(x) \in \sF$ for $x \in \R^T$ such that $\set{t \in T: x_t < \infty}$ is countable. Second, even for a simple independent process with countably infinite $T$, any function of the above form would be zero if $x_t$ is finite for all $t \in T$. Therefore, we only look at the values of $F_X(x)$ for $x \in \R^T$ where $\set{t \in T: x_t < \infty}$ is finite. That is, for any finite set $S \subseteq T$, we focus on the events $A_S(x_S)$ and their probabilities. However, these are precisely the finite dimensional distributions. Set of all finite dimensional distributions of the stochastic process $X: \Omega \to \sX^T$ characterizes its distribution completely.

:::: shaded
::: exmp
**Example 10**. Consider a probability space $(\Omega,\sF, P)$ defined by the sample space $\Omega = \set{H,T}^\N$ and the event space $\sF \triangleq \sigma(E)$ where $E_n = \set{\omega \in \Omega: \omega_n = H}$ for all $n\in\N$. Let $X: \Omega\to\set{0,1}^\N$ defined as $X_n(\omega) = \Ind{E_n}(\omega)$ for all outcomes $\omega \in \Omega$ and $n \in \N$. For this random sequence, if we are given the finite dimensional distribution $F_{X_S}: \R^S \to [0,1]$ for any finite $S \subseteq T$ and $x \in \R^S$ in terms of sets $I_0(x) \triangleq \set{i \in S: x_i < 0}$ and $I_1(x) \triangleq \set{i \in S: x_i \in [0,1)}$, as defined in Eq. [\[eqn:FDDBernoulli\]](#eqn:FDDBernoulli){reference-type="eqref" reference="eqn:FDDBernoulli"}. Then, we can find the probability measure $P: \sF \to [0,1]$ is given by
:::
::::

## Independence

::: defn
**Definition 11**. A random process is **independent** if the collection of event spaces $(\sigma(X_t): t \in T)$ is independent. That is, for all $x_S \in \R^S$, we have That is, independence of a random process is equivalent to factorization of any finite dimensional distribution function into product of individual marginal distribution functions.
:::

:::: shaded
::: exmp
**Example 12**. Consider a probability space $(\Omega,\sF, P)$ defined by the sample space $\Omega = \set{H,T}^\N$, the event space $\sF \triangleq \sigma(E)$ where $E_n = \set{\omega \in \Omega: \omega_n = H}$ for all $n\in\N$, and the probability measure $P: \sF \to [0,1]$ defined by Then, we observe that the random sequence $X: \Omega\to\set{0,1}^\N$ defined by $X_n(\omega) \triangleq \Ind{E_n}(\omega)$ for all outcomes $\omega \in \Omega$ and $n \in \N$, is independent.
:::
::::

::: defn
**Definition 13**. Two stochastic processes $X: \Omega \to \sX^{T_1},Y:\Omega\to \sY^{T_2}$ are **independent**, if the corresponding event spaces $\sigma(X), \sigma(Y)$ are independent. That is, for any $x \in \R^{S_1}, y \in \R^{S_2}$ for finite $S_1 \subseteq T_1, S_2\subseteq T_2$, the events $A_{S_1}(x) \triangleq \cap_{s\in S_1}X_s^{-1}(-\infty, x_s]$ and $B_{S_2}(y) \triangleq \cap_{s \in S_2}Y_s^{-1}(-\infty, y_s]$ are independent. That is, the joint finite dimensional distribution of $X$ and $Y$ factorizes, and
:::
